<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>PageForge.RenderSpike</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PageForge.MuPdfInterop\PageForge.MuPdfInterop.csproj" />
  </ItemGroup>

</Project>