// Copyright (c) 2026 LiVi Software Company
// SPDX-License-Identifier: AGPL-3.0-only
// This file is part of PageForge. See LICENSE for the full license text.

using System.Text.RegularExpressions;
using PageForge.Core.Pdf;
using PageForge.MuPdfInterop;
using Xunit;

namespace PageForge.Fidelity.Tests;

/// <summary>
/// Phase 1 fidelity smoke: every corpus PDF must open and render through the
/// real MuPDF shim engine, round-trip without repairs, and match its pinned
/// manifest entry (per-file page count, page-0 size and byte-pinned sha256).
/// The corpus is the real-document set generated by tools/generate-corpus.ps1
/// (contracts, forms, scans, Unicode). Golden / structural diffs against mutool
/// output are driven by the /rendercheck and /structcheck opencode commands.
/// </summary>
public sealed class CorpusSmokeTests
{
    private const byte PngSignatureByte0 = 0x89;
    private static readonly byte[] PngSignature =
        { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A };
    private const float Dpi = 96f;

    private static string CorpusDir => Path.Combine(AppContext.BaseDirectory, "corpus");

    public static TheoryData<string> CorpusPdfs()
    {
        var data = new TheoryData<string>();
        foreach (string file in Directory.GetFiles(CorpusDir, "*.pdf", SearchOption.TopDirectoryOnly))
        {
            data.Add(file);
        }

        return data;
    }

    private static (int pages, float wPt, float hPt) ManifestFor(string pdfPath)
    {
        var manifest = LoadManifest();
        string name = Path.GetFileName(pdfPath);
        Assert.True(manifest.TryGetValue(name, out var entry),
            $"{name} has no entry in manifest.psd1; regenerate or pin it.");
        Assert.True(entry.TryGetValue("pages", out var pagesObj), $"{name} manifest lacks 'pages'.");
        Assert.True(entry.TryGetValue("page0", out var page0Obj), $"{name} manifest lacks 'page0'.");

        Match dims = Regex.Match((string)page0Obj, @"(\d+)x(\d+)");
        Assert.True(dims.Success, $"{name} manifest 'page0' must be WxH points.");
        return ((int)pagesObj, float.Parse(dims.Groups[1].Value), float.Parse(dims.Groups[2].Value));
    }

    [Theory]
    [MemberData(nameof(CorpusPdfs))]
    public async Task Corpus_pdf_opens_and_renders_through_the_shim(string pdfPath)
    {
        await using MuPdfEngine engine = MuPdfEngine.Create();

        PdfDocumentInfo info = await engine.OpenAsync(pdfPath);
        Assert.True(info.PageCount >= 1, $"{Path.GetFileName(pdfPath)} must have at least one page.");

        (int pages, float wPt, float hPt) = ManifestFor(pdfPath);
        Assert.Equal(pages, info.PageCount);

        PdfPageRegion size = await engine.GetPageSizeAsync(0);
        Assert.Equal(wPt, size.WidthPt, 3);
        Assert.Equal(hPt, size.HeightPt, 3);

        RenderedPdfPage page = await engine.RenderPageToPngAsync(0, (int)Dpi);
        Assert.True(page.PngBytes.Length > 100, "Empty render output is a shim failure.");
        Assert.Equal((int)Math.Round(wPt * Dpi / 72f), page.WidthPixels);
        Assert.Equal((int)Math.Round(hPt * Dpi / 72f), page.HeightPixels);
        Assert.True(StartsWithPngSignature(page.PngBytes), "Shim output is not a PNG.");
    }

    [Theory]
    [MemberData(nameof(CorpusPdfs))]
    public async Task Every_page_renders_without_crashing(string pdfPath)
    {
        await using MuPdfEngine engine = MuPdfEngine.Create();
        PdfDocumentInfo info = await engine.OpenAsync(pdfPath);

        for (int page = 0; page < info.PageCount; page++)
        {
            RenderedPdfPage png = await engine.RenderPageToPngAsync(page, 72);
            Assert.True(png.PngBytes.Length > 100, $"page {page} of {Path.GetFileName(pdfPath)} did not render.");
        }
    }

    [Theory]
    [MemberData(nameof(CorpusPdfs))]
    public async Task Render_is_byte_deterministic_for_a_fixed_engine_build(string pdfPath)
    {
        await using MuPdfEngine engine = MuPdfEngine.Create();
        await engine.OpenAsync(pdfPath);

        RenderedPdfPage first = await engine.RenderPageToPngAsync(0, 96);
        RenderedPdfPage second = await engine.RenderPageToPngAsync(0, 96);

        Assert.Equal(first.PngBytes, second.PngBytes);
    }

    [Fact]
    public void Corpus_commit_matches_the_pinned_manifest_hash()
    {
        var manifest = LoadManifest();
        var seen = new HashSet<string>();

        foreach (string file in Directory.GetFiles(CorpusDir, "*.pdf", SearchOption.TopDirectoryOnly))
        {
            string name = Path.GetFileName(file);
            Assert.True(manifest.TryGetValue(name, out var entry),
                $"{name} has no entry in manifest.psd1.");
            Assert.True(entry.TryGetValue("sha256", out var hashObj), $"{name} manifest lacks 'sha256'.");
            string pinned = ((string)hashObj).ToUpperInvariant();
            seen.Add(name);

            using var sha = System.Security.Cryptography.SHA256.Create();
            using var stream = File.OpenRead(file);
            string actual = Convert.ToHexString(sha.ComputeHash(stream));

            Assert.True(string.Equals(actual, pinned, StringComparison.Ordinal),
                $"{name} drifted from its pinned manifest sha256.\n  pinned: {pinned}\n  actual: {actual}");
        }

        foreach (string expected in manifest.Keys)
        {
            Assert.True(seen.Contains(expected),
                $"manifest pins {expected} but the file is not in the corpus/ directory.");
        }
    }

    private static Dictionary<string, Dictionary<string, object>> LoadManifest()
    {
        var result = new Dictionary<string, Dictionary<string, object>>(StringComparer.Ordinal);
        string file = Path.Combine(CorpusDir, "manifest.psd1");
        string text = File.ReadAllText(file);

        // Each entry: 'NAME' = @{ key = value; ... }
        foreach (Match block in Regex.Matches(text, @"'([^']+\.pdf)'\s*=\s*@\{([^}]*)\}", RegexOptions.Singleline))
        {
            string name = block.Groups[1].Value;
            var fields = new Dictionary<string, object>(StringComparer.Ordinal);
            foreach (Match kv in Regex.Matches(block.Groups[2].Value,
                         @"(\w+)\s*=\s*('([^']*)'|(\d+))", RegexOptions.Singleline))
            {
                string key = kv.Groups[1].Value;
                string value = kv.Groups[3].Success ? kv.Groups[3].Value : kv.Groups[4].Value;
                fields[key] = key == "pages" ? int.Parse(value) : value;
            }

            result[name] = fields;
        }

        Assert.True(result.Count > 0, $"manifest.psd1 at {file} parsed no entries.");
        return result;
    }

    private static bool StartsWithPngSignature(byte[] bytes)
    {
        if (bytes.Length < PngSignature.Length || bytes[0] != PngSignatureByte0)
        {
            return false;
        }

        for (int i = 0; i < PngSignature.Length; i++)
        {
            if (bytes[i] != PngSignature[i])
            {
                return false;
            }
        }

        return true;
    }
}
