# Copyright (c) 2026 LiVi Software Company
# SPDX-License-Identifier: AGPL-3.0-only
# This file is part of PageForge. See LICENSE for the full license text.
# PageForge Phase 1 real-document fidelity corpus (generated by
# tools/generate-corpus.ps1). Every corpus PDF + golden render is byte-pinned
# here; a drift in any sha256 blocks the merge. Manifest is keyed by file name
# so the fidelity harness can resolve per-file page counts and page-0 sizes.

@{
  'contract-multipage.pdf' = @{
    name     = 'contract-multipage.pdf'
    source   = 'tools/generate-corpus.ps1 (realistic multi-page contract)'
    sha256   = '4F4E3B16361623F92037E9383D1408A2938DDDCAD722A42AD54145DC432FF88A'
    pages    = 4
    page0    = '612x792'
    golden   = 'golden/contract-multipage.p1.png'
    expected = '4 pages, 612x792pt, title + body + signature pages'
  }
  'form-application.pdf' = @{
    name     = 'form-application.pdf'
    source   = 'tools/generate-corpus.ps1 (AcroForm text field + checkbox)'
    sha256   = 'EDE21BC5F63F75C335F7484B87629E851D9F19F8CA61CC812DC113B31BF64634'
    pages    = 1
    page0    = '612x792'
    golden   = 'golden/form-application.p1.png'
    expected = '1 page, 612x792pt, with AcroForm fields FullName + Consent'
  }
  'scan-letters.pdf' = @{
    name     = 'scan-letters.pdf'
    source   = 'tools/generate-corpus.ps1 (raster scan proxy, image-only pages)'
    sha256   = '2C53420D45D4205169E1D5D38AC8AC050B4A479E78C43E02B63D4801D0A99504'
    pages    = 2
    page0    = '612x792'
    golden   = 'golden/scan-letters.p1.png'
    expected = '2 pages, 612x792pt, image-only raster pages'
  }
  'unicode-multilingual.pdf' = @{
    name     = 'unicode-multilingual.pdf'
    source   = 'tools/generate-corpus.ps1 (Latin-1 accented text)'
    sha256   = '351AAD4733C2F779EDFFDCAAD228434EDC0F641F892D7C0CBEBF7D196479543E'
    pages    = 2
    page0    = '612x792'
    golden   = 'golden/unicode-multilingual.p1.png'
    expected = '2 pages, 612x792pt, Latin-1 accented text'
  }
}
